# Lychee config for built-site scanning

# Base URL for resolving absolute paths in offline mode
base = "https://3mpwrapp.pages.dev"

# Exclude domains that frequently block bots or are managed externally.
exclude = [
  "https://x.com/.*",
  "https://twitter.com/.*",
  "https://www.instagram.com/.*",
  "https://www.facebook.com/.*",
  "https://docs.google.com/.*",
  "https://github.com/3mpwrApp/3mpwrapp.github.io/settings/pages",
  "https://3mpwrapp.github.io/sitemap.xml",
  "https://3mpwrapp.pages.dev/curation.*"
]

# Accept 403 for some guarded endpoints if they slip through.
accept = [200, 204, 206, 403]

# Skip repo docs if they ever appear in _site accidentally.
exclude_path = [
  ".*/_site/README\\.md$",
  ".*/_site/CONTRIBUTING\\.md$",
  ".*/_site/ACTIVATION\\.md$",
  ".*/_site/HOW_TO_ACTIVATE\\.md$",
  ".*/_site/\\.github/.*"
]

# Retries to reduce transient failures.
max_retries = 2
retry_wait_time = 2
