/**
 * DisclaimerBanner - Legal Protection Component
 * 
 * Displays comprehensive disclaimers to protect the app, developer, and users.
 * Required on all screens providing health, legal, or advisory information.
 * 
 * LEGAL PROTECTION:
 * - Medical advice disclaimer
 * - Legal advice disclaimer  
 * - Liability limitation
 * - Professional services notice
 * - Crisis intervention notice
 * - Data privacy notice
 */

import { Ionicons } from '@expo/vector-icons';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

import { MAX_FONT_SCALE } from '../hooks/useA11y';
import { useTranslation } from '../i18n';
import { useAppPalette } from '../theme/usePalette';

export type DisclaimerType = 
  | 'medical'      // Wellness, symptom tracking
  | 'legal'        // Advocacy, rights, forms
  | 'general'      // All other screens
  | 'crisis'       // Emergency/crisis resources
  | 'ai'           // AI-generated content
  | 'financial';   // Benefits, financial advice

interface DisclaimerBannerProps {
  type?: DisclaimerType;
  customText?: string;
  compact?: boolean;
}

export default function DisclaimerBanner({ 
  type = 'general',
  customText,
  compact = false,
}: DisclaimerBannerProps) {
  const palette = useAppPalette();
  const { t } = useTranslation();
  const styles = React.useMemo(() => createStyles(palette), [palette]);

  const getDisclaimerText = () => {
    if (customText) return customText;

    switch (type) {
      case 'medical':
        return t(
          'disclaimer.medical',
          '⚕️ NOT MEDICAL ADVICE: This app provides information only. It does not replace professional medical advice, diagnosis, or treatment. Always consult qualified healthcare providers for medical decisions. In emergencies, call 911 or your local emergency services.'
        );
      
      case 'legal':
        return t(
          'disclaimer.legal',
          '⚖️ NOT LEGAL ADVICE: This app provides general legal information only. It does not constitute legal advice or create an attorney-client relationship. Laws vary by jurisdiction. Consult a licensed attorney for legal advice specific to your situation.'
        );
      
      case 'crisis':
        return t(
          'disclaimer.crisis',
          '🆘 EMERGENCY NOTICE: This app is not a substitute for emergency services. If you or someone else is in immediate danger, call 911, go to the nearest emergency room, or contact a crisis hotline (988 Suicide & Crisis Lifeline in US/Canada).'
        );
      
      case 'ai':
        return t(
          'disclaimer.ai',
          '🤖 AI-GENERATED CONTENT: This content is generated by artificial intelligence and may contain errors, inaccuracies, or outdated information. Always verify important information with qualified professionals. AI should not replace professional judgment.'
        );
      
      case 'financial':
        return t(
          'disclaimer.financial',
          '💰 NOT FINANCIAL ADVICE: This app provides general information about benefits and financial assistance. It does not constitute financial, tax, or investment advice. Consult qualified financial advisors or benefits specialists for guidance specific to your situation.'
        );
      
      case 'general':
      default:
        return t(
          'disclaimer.general',
          '⚠️ DISCLAIMER: This app provides general information and support tools. It does not replace professional advice (medical, legal, financial, or otherwise). Users are solely responsible for their decisions and actions. The app developer assumes no liability for outcomes resulting from app use. See Terms of Service for complete legal protections.'
        );
    }
  };

  const text = getDisclaimerText();

  if (compact) {
    return (
      <View style={styles.compactContainer} accessibilityRole="alert">
        <Ionicons 
          name="information-circle" 
          size={16} 
          color={palette.warning} 
          style={styles.compactIcon}
        />
        <Text 
          style={styles.compactText}
          maxFontSizeMultiplier={MAX_FONT_SCALE}
          accessibilityLabel={`Disclaimer: ${text}`}
        >
          {text}
        </Text>
      </View>
    );
  }

  return (
    <View 
      style={styles.container} 
      accessibilityRole="alert"
      accessibilityLabel={`Important disclaimer: ${text}`}
    >
      <View style={styles.header}>
        <Ionicons 
          name="warning" 
          size={20} 
          color={palette.warning} 
          style={styles.icon}
        />
        <Text style={styles.title} maxFontSizeMultiplier={MAX_FONT_SCALE}>
          {t('disclaimer.title', 'Important Disclaimer')}
        </Text>
      </View>
      <Text style={styles.text} maxFontSizeMultiplier={MAX_FONT_SCALE}>
        {text}
      </Text>
    </View>
  );
}

function createStyles(palette: ReturnType<typeof useAppPalette>) {
  return StyleSheet.create({
    container: {
      backgroundColor: palette.surface,
      borderLeftWidth: 4,
      borderLeftColor: palette.warning,
      borderRadius: 8,
      padding: 12,
      marginVertical: 12,
      shadowColor: palette.text,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    icon: {
      marginRight: 8,
    },
    title: {
      fontSize: 16,
      fontWeight: '700',
      color: palette.warning,
    },
    text: {
      fontSize: 14,
      lineHeight: 20,
      color: palette.text,
      opacity: 0.9,
    },
    compactContainer: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      padding: 8,
      backgroundColor: palette.surface,
      borderRadius: 6,
      marginVertical: 8,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: palette.warning,
    },
    compactIcon: {
      marginRight: 6,
      marginTop: 2,
    },
    compactText: {
      flex: 1,
      fontSize: 12,
      lineHeight: 18,
      color: palette.text,
      opacity: 0.85,
    },
  });
}
