/**
 * Seed script to add calendar events to Firestore
 * Usage: node seed-events.js [production|preview]
 */

import { cert, initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load Firebase credentials
const serviceAccountPath = path.join(__dirname, '.firebase-key.json');

if (!fs.existsSync(serviceAccountPath)) {
  console.error('❌ Error: .firebase-key.json not found');
  console.error('Please run: Get-Content empowrapp-firebase-adminsdk-fbsvc-682129fd2f.json | Out-File .firebase-key.json');
  process.exit(1);
}

const serviceAccount = JSON.parse(fs.readFileSync(serviceAccountPath, 'utf8'));

// Initialize Firebase
const app = initializeApp({
  credential: cert(serviceAccount),
});

const db = getFirestore(app);

// Determine which collection to seed
const environment = process.argv[2] || 'production';
const collectionName = environment === 'preview' ? 'events_preview' : 'events_production';

console.log(`\n🌱 Seeding ${collectionName} collection...\n`);

// Comprehensive calendar events for 2025
// Includes: holidays, health awareness months, disability observances, worker awareness
const sampleEvents = [
  // CANADIAN HOLIDAYS 2025
  {
    title: 'New Year\'s Day',
    description: 'Federal holiday - Canada',
    date: new Date('2025-01-01'),
    endDate: new Date('2025-01-01'),
    location: 'Canada',
    isVirtual: false,
    category: 'holiday',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['holiday', 'federal'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Family Day',
    description: 'Observed in most Canadian provinces (3rd Monday in February)',
    date: new Date('2025-02-17'),
    endDate: new Date('2025-02-17'),
    location: 'Canada',
    isVirtual: false,
    category: 'holiday',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['holiday', 'family'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Good Friday',
    description: 'Federal holiday',
    date: new Date('2025-04-18'),
    endDate: new Date('2025-04-18'),
    location: 'Canada',
    isVirtual: false,
    category: 'holiday',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['holiday', 'religious'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Victoria Day',
    description: 'Federal holiday - Monday preceding May 25',
    date: new Date('2025-05-19'),
    endDate: new Date('2025-05-19'),
    location: 'Canada',
    isVirtual: false,
    category: 'holiday',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['holiday', 'federal'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Canada Day',
    description: 'National Day - Federal holiday',
    date: new Date('2025-07-01'),
    endDate: new Date('2025-07-01'),
    location: 'Canada',
    isVirtual: false,
    category: 'holiday',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['holiday', 'national'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Labour Day',
    description: 'Federal holiday - First Monday in September',
    date: new Date('2025-09-01'),
    endDate: new Date('2025-09-01'),
    location: 'Canada',
    isVirtual: false,
    category: 'holiday',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['holiday', 'labour', 'workers'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Thanksgiving',
    description: 'Federal holiday - Second Monday in October',
    date: new Date('2025-10-13'),
    endDate: new Date('2025-10-13'),
    location: 'Canada',
    isVirtual: false,
    category: 'holiday',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['holiday', 'thanksgiving'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Remembrance Day',
    description: 'Federal holiday - November 11',
    date: new Date('2025-11-11'),
    endDate: new Date('2025-11-11'),
    location: 'Canada',
    isVirtual: false,
    category: 'holiday',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['holiday', 'memorial'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Christmas Day',
    description: 'Federal holiday',
    date: new Date('2025-12-25'),
    endDate: new Date('2025-12-25'),
    location: 'Canada',
    isVirtual: false,
    category: 'holiday',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['holiday', 'christmas'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Boxing Day',
    description: 'Federal holiday - December 26',
    date: new Date('2025-12-26'),
    endDate: new Date('2025-12-26'),
    location: 'Canada',
    isVirtual: false,
    category: 'holiday',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['holiday', 'boxing day'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },

  // DISABILITY & ACCESSIBILITY OBSERVANCES
  {
    title: 'World Braille Day',
    description: 'Awareness of Braille and accessibility for blind and visually impaired',
    date: new Date('2025-01-04'),
    endDate: new Date('2025-01-04'),
    location: 'Canada',
    isVirtual: false,
    category: 'awareness',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['disability', 'accessibility', 'blindness', 'vision'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'International Wheelchair Day',
    description: 'Celebration of wheelchair users and mobility support',
    date: new Date('2025-03-04'),
    endDate: new Date('2025-03-04'),
    location: 'Canada',
    isVirtual: false,
    category: 'awareness',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['disability', 'mobility', 'wheelchairs'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Multiple Sclerosis Awareness Month',
    description: 'MS awareness, support, and treatment information',
    date: new Date('2025-03-01'),
    endDate: new Date('2025-03-31'),
    location: 'Canada',
    isVirtual: true,
    category: 'health',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['MS', 'neurological', 'chronic illness'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Brain Injury Awareness Month',
    description: 'Traumatic brain injury awareness, prevention, and recovery',
    date: new Date('2025-03-01'),
    endDate: new Date('2025-03-31'),
    location: 'Canada',
    isVirtual: true,
    category: 'health',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['brain injury', 'TBI', 'concussion', 'neurological'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'World Autism Awareness Day',
    description: 'Autism awareness, acceptance, and neurodiversity celebration',
    date: new Date('2025-04-02'),
    endDate: new Date('2025-04-02'),
    location: 'Canada',
    isVirtual: false,
    category: 'awareness',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['autism', 'neurodiversity', 'developmental'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Autism Acceptance Month',
    description: 'April 2025: Month-long autism acceptance awareness',
    date: new Date('2025-04-01'),
    endDate: new Date('2025-04-30'),
    location: 'Canada',
    isVirtual: true,
    category: 'awareness',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['autism', 'neurodiversity', 'acceptance'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Parkinson\'s Awareness Month',
    description: 'Parkinson\'s disease awareness, research, and support',
    date: new Date('2025-04-01'),
    endDate: new Date('2025-04-30'),
    location: 'Canada',
    isVirtual: true,
    category: 'health',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['Parkinson\'s', 'neurological', 'movement'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'National Day of Mourning',
    description: 'Remembering workers killed, injured, or made ill at work - April 28',
    date: new Date('2025-04-28'),
    endDate: new Date('2025-04-28'),
    location: 'Canada',
    isVirtual: false,
    category: 'awareness',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['workers', 'memorial', 'workplace safety', 'labour'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Mental Health Awareness Month',
    description: 'Mental health awareness, wellness, and stigma reduction',
    date: new Date('2025-05-01'),
    endDate: new Date('2025-05-31'),
    location: 'Canada',
    isVirtual: true,
    category: 'health',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['mental health', 'wellness', 'depression', 'anxiety'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Arthritis Awareness Month',
    description: 'Arthritis awareness, chronic pain support, and joint health',
    date: new Date('2025-05-01'),
    endDate: new Date('2025-05-31'),
    location: 'Canada',
    isVirtual: true,
    category: 'health',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['arthritis', 'chronic pain', 'joint health'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Lupus Awareness Month',
    description: 'Systemic lupus awareness and autoimmune disease support',
    date: new Date('2025-05-01'),
    endDate: new Date('2025-05-31'),
    location: 'Canada',
    isVirtual: true,
    category: 'health',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['lupus', 'autoimmune', 'chronic illness'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Global Accessibility Awareness Day',
    description: 'Digital accessibility, inclusion, and technology awareness',
    date: new Date('2025-05-15'),
    endDate: new Date('2025-05-15'),
    location: 'Canada',
    isVirtual: true,
    category: 'awareness',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['digital accessibility', 'inclusion', 'technology'],
    imageUrl: '',
    url: 'https://www.globalaccessibilityawarenessday.org',
    attendeeCount: 0,
  },
  {
    title: 'Ehlers-Danlos Syndrome Awareness',
    description: 'EDS and hypermobility disorders awareness and support',
    date: new Date('2025-05-01'),
    endDate: new Date('2025-05-31'),
    location: 'Canada',
    isVirtual: true,
    category: 'health',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['EDS', 'connective tissue', 'rare disease'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Celiac Disease Awareness Month',
    description: 'Celiac disease, gluten sensitivity, and digestive health',
    date: new Date('2025-05-01'),
    endDate: new Date('2025-05-31'),
    location: 'Canada',
    isVirtual: true,
    category: 'health',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['celiac', 'autoimmune', 'digestive'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Injured Workers Day',
    description: 'Solidarity with injured and ill workers - June 1',
    date: new Date('2025-06-01'),
    endDate: new Date('2025-06-01'),
    location: 'Canada',
    isVirtual: false,
    category: 'awareness',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['workers', 'workplace safety', 'solidarity'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Deafblind Awareness Month',
    description: 'June: Deafblind awareness and support in Canada',
    date: new Date('2025-06-01'),
    endDate: new Date('2025-06-30'),
    location: 'Canada',
    isVirtual: true,
    category: 'awareness',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['deafblind', 'deaf', 'accessibility'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'International Day of Sign Languages',
    description: 'Recognition of deaf culture and sign language',
    date: new Date('2025-09-23'),
    endDate: new Date('2025-09-23'),
    location: 'Canada',
    isVirtual: true,
    category: 'awareness',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['deaf', 'sign language', 'culture'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Spinal Cord Injury Awareness Month',
    description: 'September: Spinal cord injury prevention, research, and support',
    date: new Date('2025-09-01'),
    endDate: new Date('2025-09-30'),
    location: 'Canada',
    isVirtual: true,
    category: 'health',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['spinal cord injury', 'mobility', 'disability'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'Disability Employment Awareness Month',
    description: 'October: Employment and workplace inclusion for people with disabilities',
    date: new Date('2025-10-01'),
    endDate: new Date('2025-10-31'),
    location: 'Canada',
    isVirtual: true,
    category: 'awareness',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['employment', 'disability', 'inclusion'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
  {
    title: 'International Day of Persons with Disabilities',
    description: 'December 3: Promoting rights and well-being of persons with disabilities',
    date: new Date('2025-12-03'),
    endDate: new Date('2025-12-03'),
    location: 'Canada',
    isVirtual: false,
    category: 'awareness',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['disability', 'rights', 'inclusion'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },

  // COMMUNITY EVENTS
  {
    title: 'Community Accessibility Workshop',
    description: 'Workshop on accessibility rights and resources. ASL interpretation and closed captions provided.',
    date: new Date('2025-12-15T18:00:00'),
    endDate: new Date('2025-12-15T19:30:00'),
    location: 'Community Centre - 123 Main St, Toronto, ON',
    isVirtual: false,
    category: 'community',
    status: 'published',
    organizer: '3mpwrApp',
    tags: ['accessibility', 'workshop', 'community', 'education'],
    imageUrl: '',
    url: '',
    attendeeCount: 0,
  },
];

async function seedEvents() {
  try {
    let count = 0;
    
    for (const event of sampleEvents) {
      await db.collection(collectionName).add({
        ...event,
        createdAt: new Date(),
        updatedAt: new Date(),
      });
      count++;
      console.log(`✅ Added: ${event.title}`);
    }
    
    console.log(`\n🎉 Successfully seeded ${count} events to ${collectionName}!\n`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding events:', error);
    process.exit(1);
  }
}

seedEvents();
