import React from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput } from 'react-native';

import A11yPressable from '../../../components/A11yPressable';
import { HIT_SLOP_8 } from '../../../constants/a11y';
import { useAppPalette } from '../../../theme/usePalette';

export const options = { href: null };

export default function EmergencyWalletCard() {
  const palette = useAppPalette();
  const s = styles(palette);
  const [conditions, setConditions] = React.useState('');
  const [meds, setMeds] = React.useState('');
  const [contacts, setContacts] = React.useState('');

  const generate = async () => {
    try {
      const html = `
        <html><body style="font-family: sans-serif;">
          <h2>Emergency Info Card</h2>
          <p><b>Conditions:</b><br/>${escapeHtml(conditions).replace(/\n/g,'<br/>')}</p>
          <p><b>Medications:</b><br/>${escapeHtml(meds).replace(/\n/g,'<br/>')}</p>
          <p><b>Emergency contacts:</b><br/>${escapeHtml(contacts).replace(/\n/g,'<br/>')}</p>
          <p style="font-size: 12px; opacity: 0.8;">Generated by Empowr App — keep with you.</p>
        </body></html>
      `;
      const { printAsync } = await import('expo-print');
      await printAsync({ html });
    } catch {
      Alert.alert('Failed','Could not generate card');
    }
  };

  return (
    <ScrollView style={s.container} contentContainerStyle={{ padding:16 }}>
      <Text style={s.title}>Emergency Info Wallet Card</Text>
      <TextInput placeholder="Conditions (one per line)" multiline placeholderTextColor={palette.text+'77'} value={conditions} onChangeText={setConditions} style={[s.input,{ height: 120 }]} />
      <TextInput placeholder="Medications (one per line)" multiline placeholderTextColor={palette.text+'77'} value={meds} onChangeText={setMeds} style={[s.input,{ height: 120 }]} />
      <TextInput placeholder="Emergency contacts (name + phone/email per line)" multiline placeholderTextColor={palette.text+'77'} value={contacts} onChangeText={setContacts} style={[s.input,{ height: 140 }]} />
  <A11yPressable hitSlop={HIT_SLOP_8} onPress={generate} style={s.button}><Text style={s.buttonText}>Generate Card</Text></A11yPressable>
    </ScrollView>
  );
}

function escapeHtml(s: string) {
  return (s||'').replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;' } as any)[c]);
}

function styles(palette: ReturnType<typeof useAppPalette>) {
  return StyleSheet.create({
    container: { flex:1, backgroundColor: palette.background },
    title: { fontSize:22, fontWeight:'700', color: palette.text },
    input: { borderWidth: StyleSheet.hairlineWidth, borderColor: palette.muted, color: palette.text, padding: 8, borderRadius: 6, marginTop: 8 },
    button: { backgroundColor: palette.primary, paddingVertical: 10, borderRadius: 8, alignItems:'center', marginTop: 12 },
    buttonText: { color: palette.onPrimary, fontWeight:'700' },
  });
}
