name: Accessibility Audit (pa11y)

on:
  push:
  pull_request:
  schedule:
    - cron: "30 6 * * 1,4" # Mon & Thu @ 06:30 UTC
  workflow_dispatch:

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run pa11y-ci
        id: run
        run: |
          npx pa11y-ci --config .pa11yci.json --reporter json | tee pa11y-report.json

      - name: Upload pa11y report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pa11y-report
          path: pa11y-report.json

      - name: Summary
        if: always()
        run: |
          echo "## pa11y-ci report" >> $GITHUB_STEP_SUMMARY
          echo "See attached artifact pa11y-report.json for full details." >> $GITHUB_STEP_SUMMARY

