name: Accessibility Audit (pa11y)

on:
  push:
  pull_request:
  schedule:
    - cron: '30 6 * * 1,4' # Mon & Thu @ 06:30 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run pa11y-ci
        run: |
          npx pa11y-ci --config .pa11yci.json --reporter json | tee pa11y-report.json

      - name: Upload pa11y report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pa11y-report
          path: pa11y-report.json

      - name: Summarize results
        if: always()
        run: |
          echo "## pa11y-ci report" >> $GITHUB_STEP_SUMMARY
          if [ -f pa11y-report.json ]; then
            TOTAL=$(jq '.["total"] // .total // 0' pa11y-report.json 2>/dev/null || echo 0)
            PASSES=$(jq '.["passes"] // .passes // 0' pa11y-report.json 2>/dev/null || echo 0)
            ERRORS=$(jq '.["errors"] // .errors // 0' pa11y-report.json 2>/dev/null || echo 0)
            echo "Total: ${TOTAL}  Passes: ${PASSES}  Errors: ${ERRORS}" >> $GITHUB_STEP_SUMMARY
            if [ "$ERRORS" != "0" ]; then
              echo "\n### Top issues" >> $GITHUB_STEP_SUMMARY
              # Try to extract first few failing entries; pa11y-ci json may be an array of results
              jq -r '(.results // .) | .[]? | select(.issues) | "- URL: " + (.url // .pageUrl // "") + " (" + ((.issues | length) | tostring) + " issues)"' pa11y-report.json | head -n 10 >> $GITHUB_STEP_SUMMARY || true
            fi
          else
            echo "No pa11y-report.json found." >> $GITHUB_STEP_SUMMARY
          fi

