name: Daily Curator

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

on:
  schedule:
    # 17:00 & 18:00 UTC cover 1PM Toronto across DST changes
    - cron: '0 17,18 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  curate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: (Optional) install transient deps
        run: |
          npm install --no-save node-fetch@3 || true

      - name: Time gate (Toronto 13h)
        id: gate
        run: |
          HOUR=$(TZ=America/Toronto date +%H)
          echo "Toronto hour: $HOUR"
          if [ "$HOUR" = "13" ]; then echo "run_curate=true" >> $GITHUB_OUTPUT; else echo "run_curate=false" >> $GITHUB_OUTPUT; fi

      - name: Skip summary
        if: steps.gate.outputs.run_curate != 'true'
        run: |
          echo "## Daily curator" >> $GITHUB_STEP_SUMMARY
          echo "Skipped - not 1pm Toronto time." >> $GITHUB_STEP_SUMMARY

      - name: Run curator
        if: steps.gate.outputs.run_curate == 'true'
        env:
          MIN_SCORE: 0.5
          FORCE_DAILY: 1
          DEBUG_CURATOR: 1
          WRITE_JSON: 1
          FILTER_LANGS: en,fr
        run: node scripts/daily-curator.js

      - name: Commit and push (curation output)
        if: steps.gate.outputs.run_curate == 'true'
        run: |
          git config --global --add safe.directory "$(pwd)"
          git config user.email "actions@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add _posts/*.md _curation/*.md public/curation-latest.json || true
          git commit -m "chore(curator): daily summary" || echo "No changes"
          git push || echo "No push"

      - name: Cleanup empty curation files
        if: steps.gate.outputs.run_curate == 'true'
        run: node scripts/cleanup-empty-curation.js

      - name: Upload artifacts
        if: steps.gate.outputs.run_curate == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: daily-curation
          path: |
            _curation/*.md
            _posts/*daily-curation.md

      - name: Success summary
        if: steps.gate.outputs.run_curate == 'true'
        run: |
          echo "## Daily curator" >> $GITHUB_STEP_SUMMARY
          echo "Completed at 1pm Toronto time." >> $GITHUB_STEP_SUMMARY

      - name: Post to Mastodon
        if: steps.gate.outputs.run_curate == 'true'
        continue-on-error: true
        env:
          MASTO_INSTANCE: ${{ secrets.MASTO_INSTANCE }}
          MASTO_TOKEN: ${{ secrets.MASTO_TOKEN }}
          SITE_URL: https://3mpwrapp.pages.dev/
          MASTO_VISIBILITY: public
        run: node scripts/post-mastodon.js || echo "Mastodon post skipped or failed"