name: Daily Curator

on:
  schedule:
    - cron: '0 17,18 * * *' # Run at 17:00 and 18:00 UTC to cover 1pm Toronto across DST
  workflow_dispatch:

jobs:
  curate:
    permissions:
      contents: write
    concurrency:
      group: daily-curator
      cancel-in-progress: true
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check 1pm Toronto time gate
        id: timegate
        run: |
          TORONTO_HOUR=$(TZ=America/Toronto date +%H)
          echo "Toronto hour: ${TORONTO_HOUR}"
          if [ "$TORONTO_HOUR" = "13" ]; then echo "is13=true" >> $GITHUB_OUTPUT; else echo "is13=false" >> $GITHUB_OUTPUT; fi

      - name: Summary (skipped by time gate)
        if: steps.timegate.outputs.is13 != 'true'
        run: |
          echo "## Daily curator" >> $GITHUB_STEP_SUMMARY
          echo "Skipped because current time in Toronto is not 13:00 (1pm)." >> $GITHUB_STEP_SUMMARY

      - name: Run curator
        if: steps.timegate.outputs.is13 == 'true'
        run: node scripts/daily-curator.js

      - name: Commit and push
        if: steps.timegate.outputs.is13 == 'true'
        run: |
          git config --global --add safe.directory "$(pwd)"
          git config user.email "actions@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add _posts/*.md _curation/*.md || true
          git commit -m "chore(curator): daily summary and draft post" || echo "No changes to commit"
          git push

      - name: Upload curation artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: daily-curation
          path: |
            _curation/*.md
            _posts/*daily-curation.md

      - name: Summary (ran at 1pm Toronto)
        if: steps.timegate.outputs.is13 == 'true'
        run: |
          echo "## Daily curator" >> $GITHUB_STEP_SUMMARY
          echo "Ran at 1pm America/Toronto. See artifacts for curation summary and draft post (if generated)." >> $GITHUB_STEP_SUMMARY

      # Optional: Mastodon auto-post (free). Requires MASTO_INSTANCE, MASTO_TOKEN secrets.
      - name: Post to Mastodon
        if: steps.timegate.outputs.is13 == 'true'
        run: node scripts/post-mastodon.js