name: Daily Curator

on:
  schedule:
    - cron: '0 17,18 * * *' # Run at 17:00 and 18:00 UTC to cover 1pm Toronto across DST
  workflow_dispatch:

jobs:
  curate:
    permissions:
      contents: write
    concurrency:
      group: daily-curator
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Check 1pm Toronto time gate
        id: timegate
        run: |
          TORONTO_HOUR=$(TZ=America/Toronto date +%H)
          echo "Toronto hour: ${TORONTO_HOUR}"
          if [ "$TORONTO_HOUR" = "13" ]; then echo "is13=true" >> $GITHUB_OUTPUT; else echo "is13=false" >> $GITHUB_OUTPUT; fi

      - name: Run curator
        if: steps.timegate.outputs.is13 == 'true'
        run: node scripts/daily-curator.js

      - name: Commit and push
        if: steps.timegate.outputs.is13 == 'true'
        run: |
          git config --global --add safe.directory "$(pwd)"
          git config user.email "actions@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add _posts/*.md _curation/*.md || true
          git commit -m "chore(curator): daily summary and draft post" || echo "No changes to commit"
          git push

      - name: Upload curation artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: daily-curation
          path: |
            _curation/*.md
            _posts/*daily-curation.md

      # Optional: Mastodon auto-post (free). Requires MASTO_INSTANCE, MASTO_TOKEN (not set by default).
      # - name: Post to Mastodon
  #   if: ${{ steps.timegate.outputs.is13 == 'true' }}
      #   env:
      #     MASTO_INSTANCE: ${{ secrets.MASTO_INSTANCE }}
      #     MASTO_TOKEN: ${{ secrets.MASTO_TOKEN }}
      #   run: |
      #     echo "Stub for Mastodon posting; add secrets to enable."