# Weekly curator workflow: generates a weekly summary post.
# Runs every Monday at 13:20 Toronto time (18:20 UTC during DST / 18:20/19:20 seasonal) using two crons
# and can be triggered manually.

name: weekly-curator

on:
  workflow_dispatch:
  schedule:
    # 13:20 America/Toronto -> 17:20 or 18:20 UTC depending on DST.
    - cron: '20 17 * * 1' # winter (UTC-5)
    - cron: '20 18 * * 1' # summer (UTC-4)

jobs:
  build-weekly:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Generate weekly update post
        run: |
          node scripts/generate-weekly-post.js
      - name: Commit weekly post if changed
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@users.noreply.github.com'
          git add _posts/*weekly-update-week-*.md
          if git diff --cached --quiet; then
            echo 'No weekly post changes to commit.'
          else
            git commit -m 'chore: weekly curator post'
            git push || echo 'Push failed (possibly race).'
          fi
      - name: Upload weekly post artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: weekly-post
          path: _posts/*weekly-update-week-*.md
