name: Weekly Blog Update

on:
  schedule:
    - cron: "0 9 * * 1" # Every Monday at 09:00 UTC
  workflow_dispatch:

jobs:
  weekly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node to generate weekly from What's New
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Generate post
        run: node scripts/generate-weekly-post.js

      - name: Commit and push
        run: |
          git config user.email "actions@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add _posts/*.md
          git commit -m "chore(blog): weekly automated update" || echo "No changes to commit"
          git push

      - name: Summary
        if: always()
        run: |
          echo "## Weekly blog generator" >> $GITHUB_STEP_SUMMARY
          echo "If a new post was created it has been committed to _posts/." >> $GITHUB_STEP_SUMMARY